name: Lint Check

# CINTENT >> MANUAL_TRIGGER
# on: [push, pull_request]
on: [repository_dispatch, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        
      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # CINTENT >> CHANGE_VERSION
          # python-version: '3.x'
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy black pycodestyle pydocstyle

      - name: Run linters
        run: |
          mypy guibot
          black --check --diff --color guibot
          # only excluded checks are conflicts with black and within pycodestyle
          pycodestyle --ignore=E203,E501,W503 guibot

          pydocstyle guibot
          
      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}